version: '3.8'

services:
  webmetalslug:
    build: .
    volumes:
      - ./app:/app
    ports:
      - "9092:9092"
    restart: unless-stopped  
    networks:
      - nbridge
networks:
  nbridge:
    external:
      name: nbridge
